apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdns-recursor-internal
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: pdns-recursor-internal
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi
            limits:
              cpu: 4000m
              memory: 2Gi
