apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dns

  source:
    repoURL: https://github.com/bcfriesen/dns.git
    targetRevision: main
    path: overlays/production

  destination:
    server: https://kubernetes.default.svc
    namespace: dns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/resources/requests/cpu
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: applicationsets.argoproj.io
      jsonPointers:
        - /metadata/annotations/kubectl.kubernetes.io~1last-applied-configuration
    - group: ""
      kind: Secret
      name: pdns-auth-secret
      namespace: dns
      jsonPointers:
        - /data
