apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dns

resources:
  - namespace.yaml
  - rbac/
  - postgres/
  - pdns-auth/
  - pdns-recursor-internal/
  - pdns-recursor-external/
  - networkpolicy.yaml
  - pdbs.yaml
  - netpol-allow-dns-egress.yaml
  - netpol-allow-apiserver-egress.yaml
  - netpol-allow-cnpg-operator-ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: dns
      app.kubernetes.io/managed-by: argocd
    includeSelectors: false
    includeTemplates: true
